# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo4j', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.TextField(default=0),
        ),
    ]
