# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neo4j', '0002_project_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openhub', models.CharField(max_length=120)),
                ('github', models.CharField(max_length=120)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
